<?php  

$amenities = array(
	'Accepts Credit Card Payments',
	'Accepts Electronic Payments',
	'Affordable Housing',
	'All Bills Paid',
	'Balcony',
	'Basketball Court(s)',
	'Business Center',
	'Cable Ready',
	'Cable Included',
	'Ceiling Fan(s)',
	'Clubhouse',
	'Covered Parking',
	'Disability Access',
	'Dishwasher',
	'Enclosed Yards',
	'Extra Storage',
	'Fireplace',
	'Fitness Center',
	'Furnished Available',
	'Garage',
	'Garden Tub',
	'Gas Range',
	'Gated Access',
	'Hardwood Flooring',
	'High Speed Internet Access',
	'Internet Included',
	'Laundry Facility',
	'Microwaves',
	'Oversized Closets',
	'Pets',
	'Playground',
	'Se Habla Espanol',
	'Security Systems',
	'Short Term Leases Available',
	'Smoke Free',
	'Some Paid Utilities',
	'Stainless Steel Appliances',
	'Swimming Pool',
	'Tennis Court(s)',
	'Vaulted Ceilings',
	'Washer & Dryer Connections',
	'Washer & Dryer In Unit',
	'Wireless Internet Access',
	'Yards',
);

?>